// Auto-generated from starter-packs-v2.json (gate-validated). Do not hand-edit element lists;
// edit the JSON, re-run pack_validator.py, and regenerate.

export const PHONETIC_PACKS: Record<string, {start: string[]; middle: string[]; end: string[]}> = {
  "harsh": {
    "start": [
      "Ka",
      "Kro",
      "Gra",
      "Dru",
      "Gro",
      "Bra",
      "Dra",
      "Gru",
      "Kae",
      "Tro",
      "Skra",
      "Vra",
      "Zar",
      "Kor",
      "Dro"
    ],
    "middle": [
      "kta",
      "gda",
      "rka",
      "tro",
      "dra",
      "gna",
      "kra",
      "rna",
      "gto",
      "dko",
      "kar",
      "gorn"
    ],
    "end": [
      "-kar",
      "-gorn",
      "-drak",
      "-tuk",
      "-gath",
      "-korr",
      "-dun",
      "-grim",
      "-tak",
      "-druk",
      "-gnar",
      "-krag"
    ]
  },
  "soft": {
    "start": [
      "Ae",
      "Ela",
      "Mae",
      "Li",
      "Na",
      "Lae",
      "Elo",
      "Ali",
      "Nae",
      "Ona",
      "Ila",
      "Elya",
      "Oli",
      "Ma"
    ],
    "middle": [
      "lia",
      "mena",
      "noli",
      "lela",
      "ria",
      "lae",
      "moa",
      "nia",
      "lena",
      "mira",
      "lor",
      "nan"
    ],
    "end": [
      "-lian",
      "-mel",
      "-nor",
      "-lia",
      "-wen",
      "-mor",
      "-riel",
      "-len",
      "-nal",
      "-mira",
      "-lyn",
      "-nel"
    ]
  },
  "bright": {
    "start": [
      "Si",
      "Se",
      "Sha",
      "Isi",
      "Esi",
      "Sei",
      "Ti",
      "Zi",
      "Shi",
      "Sae",
      "Ise",
      "Eshi",
      "Asi"
    ],
    "middle": [
      "sil",
      "sisha",
      "sesi",
      "sita",
      "sia",
      "sse",
      "shi",
      "ssi",
      "siti",
      "sesha",
      "ser",
      "sin"
    ],
    "end": [
      "-sil",
      "-shen",
      "-tis",
      "-kis",
      "-sith",
      "-lish",
      "-sen",
      "-riss",
      "-shil",
      "-kit",
      "-sis",
      "-cen"
    ]
  },
  "grand": {
    "start": [
      "A",
      "O",
      "Aro",
      "Ola",
      "Ora",
      "Alo",
      "Amo",
      "Ono",
      "Ava",
      "Oro",
      "Aldo",
      "Auro",
      "Orda"
    ],
    "middle": [
      "nala",
      "moro",
      "nama",
      "dano",
      "dona",
      "mora",
      "lova",
      "noma",
      "daro",
      "nola",
      "mor",
      "lon"
    ],
    "end": [
      "-don",
      "-mor",
      "-thal",
      "-gorn",
      "-noth",
      "-dor",
      "-mon",
      "-rath",
      "-bal",
      "-moran",
      "-domos",
      "-daion"
    ]
  },
  "exotic": {
    "start": [
      "Zae",
      "Roi",
      "Eu",
      "Nae",
      "Voi",
      "Jae",
      "Kai",
      "Ai",
      "Qua",
      "Tsa",
      "Vae",
      "Zoi",
      "Nei"
    ],
    "middle": [
      "vaeda",
      "noira",
      "leuna",
      "naixa",
      "doela",
      "naewa",
      "luina",
      "noena",
      "vaeno",
      "neir"
    ],
    "end": [
      "-vaeth",
      "-doir",
      "-neun",
      "-nael",
      "-raen",
      "-luin",
      "-noen",
      "-zyth",
      "-vaal",
      "-teir",
      "-naum"
    ]
  }
};

export const SEMANTIC_PACKS: Record<string, {additive: boolean; concepts: string[]}> = {
  "core": {
    "additive": false,
    "concepts": [
      "strong",
      "wise",
      "noble",
      "fair",
      "bright",
      "swift",
      "brave",
      "true",
      "free",
      "high",
      "old",
      "young",
      "great",
      "fierce",
      "gentle",
      "proud",
      "bold",
      "pure",
      "dark",
      "light",
      "man",
      "woman",
      "child",
      "son",
      "daughter",
      "born-of",
      "kin",
      "elder",
      "chief",
      "lord",
      "lady",
      "guardian",
      "gift",
      "hope",
      "joy",
      "fortune",
      "blessed",
      "beloved",
      "honoured",
      "far-seeing",
      "stone",
      "river",
      "hill",
      "star",
      "sun",
      "moon",
      "sky",
      "flame",
      "wind",
      "dawn",
      "wolf",
      "hawk",
      "bear",
      "stag",
      "raven",
      "lion",
      "serpent",
      "eagle",
      "horse",
      "hound",
      "iron",
      "gold",
      "silver",
      "oak",
      "ash",
      "thorn",
      "shield",
      "spear",
      "crown",
      "oath"
    ]
  },
  "warrior": {
    "additive": true,
    "concepts": [
      "sword",
      "blade",
      "axe",
      "spear",
      "shield",
      "war",
      "battle",
      "valour",
      "victory",
      "conquest",
      "blood",
      "fury",
      "wrath",
      "iron",
      "steel",
      "banner",
      "fortress",
      "strike",
      "wound",
      "vengeance",
      "guard",
      "warband",
      "champion",
      "scar",
      "siege",
      "rally",
      "onslaught",
      "bane",
      "unbroken",
      "deathless"
    ]
  },
  "seafaring": {
    "additive": true,
    "concepts": [
      "sea",
      "wave",
      "tide",
      "salt",
      "storm",
      "harbour",
      "sail",
      "ship",
      "deep",
      "current",
      "foam",
      "anchor",
      "horizon",
      "island",
      "shore",
      "fathom",
      "gull",
      "brine",
      "reef",
      "squall",
      "voyage",
      "mast",
      "keel",
      "drowned",
      "far-shore",
      "seaborne",
      "spray",
      "leviathan",
      "beacon",
      "helm"
    ]
  },
  "mountain": {
    "additive": true,
    "concepts": [
      "peak",
      "granite",
      "cliff",
      "snow",
      "ore",
      "ridge",
      "cavern",
      "echo",
      "avalanche",
      "summit",
      "delve",
      "deep-road",
      "frost",
      "eagle",
      "chasm",
      "boulder",
      "scree",
      "glacier",
      "hold",
      "highborn"
    ]
  },
  "forest": {
    "additive": true,
    "concepts": [
      "leaf",
      "root",
      "thorn",
      "oak",
      "moss",
      "grove",
      "green",
      "hunt",
      "shadow",
      "antler",
      "briar",
      "hollow",
      "fern",
      "boar",
      "vine",
      "wildwood",
      "trail",
      "quiet",
      "undergrowth",
      "evergreen"
    ]
  },
  "arcane": {
    "additive": true,
    "concepts": [
      "rune",
      "veil",
      "spell",
      "spirit",
      "dream",
      "ward",
      "ether",
      "glyph",
      "star",
      "moon",
      "hollow",
      "whisper",
      "sigil",
      "aether",
      "unseen",
      "threshold",
      "binding",
      "far-mind",
      "twilight",
      "wyrd"
    ]
  },
  "desert": {
    "additive": true,
    "concepts": [
      "sand",
      "sun",
      "dune",
      "mirage",
      "ember",
      "scorpion",
      "dry",
      "oasis",
      "dust",
      "glare",
      "thirst",
      "wanderer",
      "caravan",
      "scorched",
      "sirocco",
      "waterless",
      "flint",
      "vulture",
      "far-road",
      "sunblind"
    ]
  },
  "mercantile": {
    "additive": true,
    "concepts": [
      "coin",
      "gate",
      "guild",
      "road",
      "market",
      "bell",
      "ledger",
      "tower",
      "key",
      "scale",
      "bridge",
      "toll",
      "banker",
      "contract",
      "quarter",
      "counting-house",
      "seal",
      "vault",
      "wheelwright",
      "highroad"
    ]
  },
  "priestly": {
    "additive": true,
    "concepts": [
      "light",
      "temple",
      "prayer",
      "saint",
      "vow",
      "dawn",
      "incense",
      "pilgrim",
      "grace",
      "ash",
      "relic",
      "hymn",
      "cloister",
      "penitent",
      "sanctified",
      "vigil",
      "sacred-fire",
      "confessor",
      "shroud",
      "benediction"
    ]
  },
  "agrarian": {
    "additive": true,
    "concepts": [
      "field",
      "grain",
      "harvest",
      "ox",
      "plough",
      "hearth",
      "seed",
      "meadow",
      "shepherd",
      "orchard",
      "furrow",
      "millstone",
      "cattle",
      "well-fed",
      "sunlit",
      "homestead",
      "scythe",
      "fallow",
      "greenrow",
      "goodhearth"
    ]
  }
};
